development:
  adapter: postgresql
  encoding: unicode
  database: vietnam_club_development
  pool: 5
  username: postgres
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: vietnam_club_test
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: vietnam_club_production
  pool: 5
  username: postgres
  password: